---
- project:
    check:
      jobs:
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
    post:
      jobs:
        - stx-manifest-upload-git-mirror

- job:
    name: stx-manifest-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/manifest to
      github.com/starlingx/manifest
    vars:
      git_mirror_repository: starlingx/manifest
    secrets:
      - name: git_mirror_credentials
        secret: stx-manifest-github-secret2
        pass-to-parent: true

- secret:
    name: stx-manifest-github-secret2
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      ssh_key: !encrypted/pkcs1-oaep
        - Ki0CGI5OyW77vA7eVfU+yc0SfMV4DPnjPaVn/NZNVFogn9lEPOH4Erl8ZT//ESl78WIFy
          bqx5wWf6waNpWPLQmMT1wLQrYmMmOMPzWidkF71WFL4YeA7o1arRVvQNWfJHOmDZZOfF6
          DGQvJp5QZPxOVDPt7vHTD7lGGSnsUWHhUnxddIf17GGxLNlvoXRn0owToEAg6OpdJPa8k
          6jqXIm5f/Elb1pepWBkmZwv2PwEtiyYjzpspFM/j4BbYk2UIxb+KdYmmmZRADuoMGqPmD
          b9C5rd5tOb7BaKISaYFrvBKATRGv5XbUnlO61w0gHgEugnykKtSJkhIK9sOR/HadL0zJ1
          D1SVmInUAhB6CKFQ9LYcoCMpKuuaVJeQML2jR9CjWOLCveyw7ybOyQep58GyRVoHxotvC
          b4MGvnC0JRynV2k7N/oPAqFtbV7omeFVjKN7RlVKeQ/cft/r0o8687zqzTS7zWdvyUQ71
          BHVPhe0XTZzTGrtqtBf4cPDIPhtTLjNEpFYVW5ixoqlpBAVdcbXYgPc302uepXMuJb+Bw
          yXbJyUO+YhWY4SRxH0pgBmy3pbpTCpvLWROX9vH9kqhWGAi4FEaO4ak1O6vXbkvP2uoKM
          7YX02QF2Rvuhk1TPopC8KibByUc156eHYo+exd2ZKzlXzVhqgeeLi9HMfYMXeA=
        - VYddIz4yRNz+LbUqlpOg2ZHzAo91QfEeDrxw53N11UTrk/QMFBDRkRcOhe99xz1nH80NB
          W5wWLmA4JBF5DRURjdt4wdDPdlmKQb+0Oc3aZWzigmwCQgXkvPtK0rPeYWyWjEAWOV4gw
          GXUiIMCYMHpKvDckV3f9qZdwDuIxnQQK8F7dtLxKhjbeKdHpTE5TESGI+qTLR9yTQdT0W
          c/U4mejPx4F4S9Av6PweQTyxMqTYVqyvKb2VpAyUNNdGLqdL93DBLxfgUg0kLaXBA+6Iy
          WZYp6CkMaiSM8aGmBWWBXe3OPdy/AhaEcB+DJp4tvKkqqjLTNwJ2wZnLVq8lxt9VrZtJg
          BsZqrn6m9R+KEMDM5IhO3iuXzZOlkTlKplwML9ZtJTDgQaLpYW4qX2AP8rzGUy3kL5DEO
          yF6NBUNbCORhs7DYIFPpJOnY4VeZFuUHYSYJtjr/STq+Zx+Jq+APXsHhRCyKX0T+uGAL2
          1fllGjFy09/55Nc3wB+y/qKin62rehjo/aRmClqIg/qhv36NnAOydRBDvA/kZdWEySnfc
          v0fYqvpesIl50nat1WVF3+9VTlKAca+KJLeQ6XUxOw8Tb+N55pTcIj6yENlt0ilXFzxGz
          Z4M8h0HK9S2AkJr1J8XccM/OZt71dWyjMf292DxuABrAuRymzKNcQPJ0ypPosY=
        - AN7VNPGjGbK9tdFHbZNsL7hsr/3nKkCt2gfzAF8XEheQDX2VEyOU9jBzQBwIBIxRwVjF0
          LBv4Kb2BDqeuKNl7WHmhqgrMWumXqVsgRtpUGmOJCokDR/wv7NeeYp0aye+RLOzhyOVFL
          Kk2OCFERaelP4ofTWC1yZXl34oepSFyTj/JhPoJPiqAHbzH1T1yB4yTNq3wdeQUDZZQQF
          3boNxF3D/xdIQxfTMJqMwT0mnFfC14RHBtdBfX6dSd8pckFx6qJ6WFz78L2s8kE+LOBNB
          FOv6Ts2iN53vbdAJ/EJIyJ/BLLXhfivugO56s6SAxtU5ttzNmwbZb0xWhzVzZG37O10my
          PzJHpY920MD0XU57GKg90ubtgDrj7E0PzihXW1bTr8W6+R9M1NgVEl3LgFnnWB1jmh0xr
          Zy54DJ0bfHb/LoDInEVWTqgVflHS82THDhjZ39oAp1mKcSYB5tfSRDTmnD0cLkQmmi2mZ
          in2MF9RHgjJryV3v2b/tmYeCFwS/nb6CpzPaBgF5MX+D80J1BpR9ort+u86cVIZ/Mtfgw
          s6D1iJe5/0Xqqpn/ze9J720/rQANQNPvF6QjTNFlLbrV94IjP4twbuQxmVXZwjUkXta3D
          4VtY7+UiEdug06pV51Zu3z6fLfB6UVC+DHiNOs0BTmRPq/bMD0Fm9aS0qwicMA=
        - dehlGBC8q6o2OcxbqrpbfFYq2EQuWrG08PN9aHSfxQ3+5UxO666zV/7/xWhF5r1tpksz0
          Ll2kDHZkXZLdJVxh8Xqug4UbXCAze+Mh1BzgF/zUugTJMwHon4bBbXFlE766fFDc9Q0fQ
          ejfwwBgNVPlvPyHX1FZVzoTY9NdlMloNkymVwjAGbcv61EV5RcudLgrd0O6VFsiYaKho/
          FEP/yuUlFjKZAC+72nBetRfa5limhvpv1rzdF9ZzmDdWoH2nsg3/vOlupDTDxnfh6xfKc
          wXWGo/w6Fxf3+xLhgLTA3acmYbAfWRZSdsX2gNzsNV/+O9JO2yfReUdSwJTmi0fxG3RGS
          YTKNOLoXlwYSW/bxhIONqSoCR5APrI4HEBpkQm7yRDDtMR8VdLboG+1apSkmeTac5+V1F
          S5rjXjuzswh7m4ruFUMoRGdh9/YE99+05oUNDpTrYCqIx+9eEGtClaKWpKxz5fpRFycS/
          rEXNfnIUbnSF62IqJ5jrtc9rgPzAUImO04fQO9yO/lE0t8nwEptvZcWEBzWlFXjCD1w8L
          9W/x3fssRNu2RdqiScHO0E7f9QcbLx/DdSodjLsZ0JS+hPH5NBD+H7io56Xhq30b0r7WZ
          n/q31B//NuuPkiYsMQg7ewKMh0HJDn142f+nRRJVZJqOctyHLEsqyhXR9+c1fI=
        - bkFe4ZyrhqreZvtOccr1Am+GnIH7N1pPvHonLcexTKlTt2o63eXvI+OdEWBIR41tgR/tU
          qP8IHnh5S12RzR2L2wA3PZ6aGBs8qPo6gT29sP4+P5XlPwrrveELCEAsjYHWidQuXBjQg
          FWJeBoIgxCSYYeahiTqYuujhEM05iZ/9/dOo/x9OU8vPVl0To8hwfBeasZlfj/Qrs3OUx
          d8uK/lwVeFMQHXLRWmaZfPvkPe4r3UZg+5GJazNDN5AsIHj5K3VIilH8N0tHlxlFbeNOq
          I75ChGXlByiMHdOVUEIGKnrjtlG/Y50ASMv3O2oAzhgHN+oBnyAgGppDMNx74LkOhb7o0
          EYHdpGtNEYlu48HoRkvBzUqF1BNc4lXxrALXdsWTEYI4G1jxVgLsfeMDEZSdFAksjOAZz
          nOSqX1OHp+FFoYcXQBvYMkeluTL3sd6WJqEe9ey+gGpG2Vf5RlXFedgkFtAg5hke8em1C
          Ikll3EW00/GovOSNoQLyCxCvNTMbQLATftQzLr3gmVICm1v9Zwny0EpvnlD7IHwVexVe7
          cr7DlFW2QuYhK3Yl9HbNHsSEKaS2a34PB9/rh7i+3jbAvXyHPtTKVj+451guijpdAJ+Ia
          gbf7VOUEcA83JyJABoh7/n82xe01TpcOsif4fWGbJ4T+Khji9geVHKG24QjbWU=
        - LZUd2iJzbvtTA7V0+cH1k8o95O8Mn6nYofAO+nhfIbN2LRC5pJANaQfNO5nZv5JK7ItFn
          mpkok0j17S7EuWBvGQ3auKHdb7iasbpO0rasK2nzDZXAPdm9RuFpVl4DkZegGp6xcGEZ3
          PebBRtIYhIExbbwP24jDcGiQob8WF8NG9y4zNAU0YxQlJNcrpLYvDr0bGP76RSzGAIFGO
          77+hVuZczDe04Ov7ycZ/MzLQJfcZXH5Ix0/4q6eArV1HB7Sz/qXPBjn7MqGN7bQscZWYQ
          3Ub8tm9dW1cucMVJ6u1aGqRlBNNznEXLdDMeBMQ4cggGRQreHjs2USvTn4VN33nP4399+
          1QidqC3lOcNMr6u7iePT8xh3i+SmbIRTifuvJ/vW/Mr+Ze0UMAAEGe9S3bPi4092XXOBp
          q2yVrRE2R4mwPIoueh/dndFvDMd5KVFxbSnlMYLC23JNdIRFYnT7EeHSa3GOuaMSvPS0O
          B0MqU98AL5+qs3+5L2CcYByYj4JjNp3Xc/Q9ESI/hDieh/7+SiIrNyRRnk0fOOYUHOxwI
          41lJ1B/YtLTCdyS9O+4Xds2zPdtqNEq6DTpa0CgIgyGnrA8QUFl4vQYYO2Cq4qEWE4hDu
          YXfmkGztj0W2ut2ZViRx6ph/3d9IptGHdPgpPHb8fnYTbugBDav+99ND3f7wzM=
        - kVdL2WhtjDhRtthz2k2Wd9nKelopkCnbVJIyQCUQbm1OyNvXR7Lax8ldJoOF/bMLWBi7B
          NCA6sW0dhaR8/f8+jJzZ9eRsfF/8JK8t03lyZU4ho6E4QqqLPcNmX84VHW5p4ODYSTdHY
          2GMWrjCCAKF3RufQh4oxegqSAHSg/X98lR7IiT+yixf1jR4hgv917ff7hpmOBbPT5Hbp3
          0CXAy6bG34EIJcLp7kYZ0Fm1qd0EZkG9fIGxMYMAJx71HEVz3hl9qDHxSmsiwl13eTK15
          QYvFbKEU7Oopheb8Yv1peYInVtyfRF4H5pgFXGhGIbtPkVLjQTyuluQ+XRGsefTuIiUDq
          +plo1Qf6lGTmy3MynAqnXaWD9e+S74/aUx+SSn7LpDoR83e2ZDKYYJkyNsFXpSVHYvdot
          jkc7vhBTnAJOikgDmNYpuhA7q/CZpOvnK5XnROEkskBywgRLiUB5i2vTtV9B2ovM/D75U
          VJRLdHBcppu7S3Vhqe/s0ECRvP4RPBb0Nr0xXqA3ZtATwxs6V9mL4wYOqcTPKixTaP3y8
          +vE5ilU1kutdNJg2wV8+Hw4jbE174a2ea0b/AkiwhtBQWcD35s5ZEzrRRddkQg/YlhpQ4
          /NcT0r+iPbUwDlVKy3KPfKQ0OIx/iwFRL1BaN0bEyafv5tfaHPAyGSuxKbXHJY=
